urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings
from django.contrib import admin
from surlex.dj import surl
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
   )

urlpatterns += patterns('',
    url(r'^login/', 'monitor.views.login_user', name='login'),
    url(r'^logout/', 'monitor.views.logout_user', name='logout'),
    surl(r'^get-group/<group_id>/$', 'monitor.views.group_data', name='get_group'),
    surl(r'^get-site/<site_id>/$', 'monitor.views.site_data', name='get_site'),
    surl(r'^outages/$', 'monitor.views.outages', name='outages'),
    surl(r'^outage/<outage_id>/$', 'monitor.views.outage', name='outage'),
    surl(r'^outage-<code>/$', 'monitor.views.outage', name='outage_code'),
    surl(r'^outage/$', 'monitor.views.outage', name='current_outage'),
    url(r'^', 'monitor.views.home', name='home'),
)   

monitor/models.py
from django.db import models

class Group(models.Model):
    """
    Group sites by type
    """
    title = models.CharField(max_length=50)
    
    def __unicode__(self):
        return self.title
    
PRIORITY_CHOICES = ((3,'Low'),
                    (2,'Normal'),
                    (1,'High'),
                    (0,'Critical'))

class Site(models.Model):
    """
    Core information about a site
    """
    title = models.CharField(max_length=40)
    url = models.URLField()
    is_active = models.BooleanField(default = True)
    down_message = models.CharField(max_length = 140, default="There is a problem with the website.")
    last_seen = models.DateTimeField(null=True, blank=True, default=None)
    down_count = models.IntegerField(default = 0)
    group = models.ForeignKey(Group)
    priority = models.IntegerField(choices=PRIORITY_CHOICES, default=2)
    
    def __unicode__(self):
        return self.title
    
class SiteView(models.Model):
    """
    Records when it has been accessed and the code returned
    
    This will get big very quickly, so there will need to be a database purge 
    script written.  This shouldn't be done on save because the normal 
    monitoring system should do no extra work.
    
    Using a UUID rather than an auto-increment for the pk
    """
    uuid = models.CharField(max_length=48, primary_key=True)
    site = models.ForeignKey(Site)
    attempt_time = models.DateTimeField(auto_now_add = True)
    status_code = models.IntegerField()
    
    def __unicode__(self):
        return self.site.title + ' - ' + str(self.attempt_time)

class Outage(models.Model):
    """
    Records when an outage has taken place, including all the things that have 
    gone down and the dates when it was resolved etc
    """
    start_time = models.DateTimeField()
    content = models.TextField()
    end_time = models.DateTimeField(blank=True, null=True, default=None)
    seconds_down = models.IntegerField(blank=True, null=True, default=None)
    extra_information = models.TextField(blank=True, null=True, default=None)
    sites = models.ManyToManyField(Site, through='OutageSites')
    notification_sent = models.BooleanField(default = False)
    code = models.CharField(max_length=8)
    
    def __unicode__(self):
        return str(self.start_time)
    
    
class OutageSites(models.Model):
    """
    Records which sites are effected by the outage
    """
    site = models.ForeignKey(Site)
    outage = models.ForeignKey(Outage)  
    primary = models.BooleanField(default = False)
    start_time = models.DateTimeField()
    
    def __unicode__(self):
        return self.site.title
    
    

monitor/views.py
from django.shortcuts import render_to_response ,get_object_or_404
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.db.models import Q
from django.template import RequestContext
from django.contrib.contenttypes.models import ContentType
from scripts.my_shortcuts import render_to_hxr_response, paginate
from models import *
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse
from django.contrib import messages

def login_user(request):
    """
    Logs the user in
    """
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                messages.add_message(request, messages.SUCCESS, 'Welcome back!')
                return HttpResponseRedirect(reverse('home'))
        
        messages.add_message(request, messages.ERROR, 'We could not log you in')
        return HttpResponseRedirect(reverse('login'))
    return render_to_response('login.html',
                              context_instance=RequestContext(request))
    

def logout_user(request):
    logout(request)
    messages.add_message(request, messages.INFO, 'You have logged out')
    return HttpResponseRedirect(reverse('login'))

    
def home(request):
    """
    Show monitoring results for all systems being monitored.
    
    This doesn't do any parsing, it just gets the latest information from the 
    database.  A seperate script does the db update work.
    """
    
    if request.user.is_authenticated():
        groups = Group.objects.all()
        error_count = Site.objects.filter(is_active = True, down_count__gte = 3).count()  
        return render_to_response('home.html',
                                  {'groups': groups},
                                  context_instance=RequestContext(request))
    else:
         return HttpResponseRedirect(reverse('login'))
    
@login_required
def group_data(request, group_id):
    """
    Returns a json object containing details for each site being monitored in 
    this particular group
    """
    group = Group.objects.get(pk = group_id)
    sites = Site.objects.filter(group = group,
                                is_active = True).order_by('priority')
                                
    warning_count = sites.filter(down_count__gte = 1).count()
    error_count = sites.filter(down_count__gte = 3).count()                            
                                
    return render_to_hxr_response('group.html',
                                  {'sites': sites,
                                   'warning_count': warning_count,
                                   'error_count': error_count},
                                   context_instance=RequestContext(request))

@login_required
def site_data(request, site_id):
    """
    Returns details of the last 10 requests to view this particular site as a 
    json object
    """
    site = Site.objects.get(pk = site_id)
    recent_views = SiteView.objects.filter(site = site).order_by('-attempt_time')[:10]
    good_codes = settings.GOOD_CODES
    return render_to_hxr_response('views.html',
                                  {'recent': recent_views,
                                   'good_codes': good_codes},
                                  context_instance=RequestContext(request))

@login_required
def outage(request, outage_id=None, code=None):
    """
    Shows details of an outage, or the current outage if there is one
    """
    if outage_id is not None:
        outage = get_object_or_404(Outage, pk = outage_id)
    elif code is not None:
        try:
            outage = Outage.objects.filter(code = code).order_by('-start_date')[0]
        except:
            outage = get_object_or_404(Outage, end_time = None)
    else:
        outage = get_object_or_404(Outage, end_time = None)
        
    
    return render_to_response('outage.html',
                              {'outage': outage},
                              context_instance=RequestContext(request))

@login_required
def outages(request):
    """
    Lists all outages recorded on the system.  You can click on each one to 
    view the details of it.
    """
    outage_list = Outage.objects.all().order_by('-start_time')
    outages = paginate(outage_list, 25, request.GET.get('page'))
    
    return render_to_response('outages.html',
                              {'outages': outages},
                              context_instance=RequestContext(request))

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Website Monitoring</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Checking if a website is running">
    <meta name="author" content="Paul Horner">
    <link href="{{MEDIA_URL}}css/bootstrap.min.css" rel="stylesheet">
    <link href="{{MEDIA_URL}}css/bootstrap-responsive.min.css" rel="stylesheet">
    <!--
                     _____
                   .'/L|__`.
                  / =[_]O|` \
                  |"+_____":|      If anything goes wrong 
                __:='|____`-:__    we'll call one of our 
               ||[] ||====| []||   R2 units to come along 
               ||[] | |=| | []||   and fix it.
               |:||_|=|U| |_||:|
               |:|||]_=_ =[_||:| 
               | |||] [_][]C|| |
               | ||-'"""""`-|| |
               /|\\_\_|_|_/_//|\
              |___|   /|\   |___|   
              `---'  |___|  `---'   
                     `---' 
    -->
  </head>
  
  <body class="preview">
{% if request.user.is_authenticated %}

<div class="navbar navbar-fixed-top">
   <div class="navbar-inner">
     <div class="container">

       <div id="main-menu" class="nav-collapse pull-right">
           <ul id="main-menu-left" class="nav">
               <li><a href="{% url home %}">Monitoring</a></li>
               <li><a href="{% url outages %}">Outages</a></li>
               <li><a href="{% url logout %}">Logout</a></li>
           </ul>
       </div>
     </div>
   </div>
 </div>
{% endif %}
 
 
    <div class="container">
        <div class="row" style="margin-top:80px;">
            <div class="span8">
                <header class="jumbotron subhead" id="overview">
                  <h1>Website Monitoring</h1>
                  <p class="lead">Checking your sites so you don't have to...</p>
                </header>
            </div>
            <div class="span4">
                <div id="countdown">{% block info %}{% endblock %}</div>
            </div>
        </div>
    {% if messages %}
        {% for message in messages %}
        <div class="row">
            <div class="span12">
                <div class="alert {% if message.tags %}alert-{{ message.tags }}{% else %}alert-block{% endif %}">
                    {{ message }}
                </div>
            </div>
        </div>
        {% endfor %}
    {% endif %}


{% block section %}

{% endblock %}

    <br/><br/><br/><br/>

      <footer class="footer">
        <p class="pull-right">
            {% if request.user.is_authenticated %}
            <a href="#">Back to top</a>
            {% endif %}
        </p>
      </footer>

    </div>
    <script src="{{MEDIA_URL}}js/jquery-1.8.0.min.js"></script>
    <script src="{{MEDIA_URL}}js/bootstrap.min.js"></script>
    {% block js %}
    {% endblock %}
  </body>
</html>

templates/fragments/pagination.html
            
            <!-- Generic Pagination Links -->
            
            <div class="pagination pull-right">
                <ul>
                    <li {% if not obj.has_previous %}class="disabled"{% endif %}>
                        <a href="?page={{ obj.previous_page_number }}">«</a>
                    </li>
                    {% for page in obj.paginator.page_range %}
                    <li {% if page == obj.number %}class="active"{% endif %}>
                        <a href="?page={{page}}">{{page}}</a>
                    </li>
                    {% endfor %}
                    
                    <li {% if not obj.has_next %}class="disabled"{% endif %}>
                        <a href="?page={{ obj.next_page_number }}">»</a>
                    </li>
                </ul>
            </div>

templates/group.html
{% if error_count %}
<div class="row">
    <div class="span12">
        <div class="alert alert-error">
            Something is wrong in this group.  You need to fix it quickly!
        </div>
    </div>
</div>
{% else %}
{% if warning_count %}
<div class="row">
    <div class="span12">
        <div class="alert alert-warning">
            Something may be wrong in this group.  You should check it out.
        </div>
    </div>
</div>
{% endif %}
{% endif %}
<div class="row">
    <div class="span12">
        {% for site in sites %}
            <span class="site control-group{% if site.down_count >= 3 %} error{% else %}{% if site.down_count != 0 %} warning{% endif %}{% endif %}" name="{{site.pk}}" style="cursor: pointer;">
            {% if site.down_count >= 3 %}
                <span class="label label-important">ERROR!</span>
            {% else %}
                {% if site.down_count != 0 %}
                <span class="label label-warning">Warning</span>
                {% else %}
                <span class="label label-success">OK</span>
                {% endif %}
            {% endif %}
                <span class="{% if site.down_count != 0 %}help-inline{% else %}data{% endif %}">
                    <strong>{{site.title}}</strong> (<a href="{{site.url}}" target="_blank" title="Opens in a new window">{{site.url}}</a>) was last seen on {{site.last_seen|date:"l, jS F"}} at {{site.last_seen|date:"g:ia"}}
                    {% if site.down_count >= 3 %}
                    <strong>We have checked this site {{site.down_count}} times</strong>.
                    {% endif %}
                </span>
            </span>
            <div class="well history" id="history-{{site.pk}}" style="display:none;"></div>
            <br/>
        {% endfor %}
    </div>
</div>

<script type="text/javascript">
    $('.site').live('click', function(){
        var pk = $(this).attr('name');
        $('#history-' + pk).show();
        $('#history-' + pk).html('<img src="{{MEDIA_URL}}img/loading.gif" alt="loading" />');
        $('#history-' + pk).load('./get-site/' + pk + '/');    
    });
    $('.history').click(function(){
        $(this).hide();
    })
</script>

templates/home.html
{% extends "base.html" %}
{% block section %}

{% for group in groups %}
    <section id="group-{{group.pk}}" class="section-head" name="{{group.pk}}">
      <div class="page-header">
          <h1>{{group.title}}</h1>
      </div>
      <div id="content-{{group.pk}}">
          <img src="{{MEDIA_URL}}img/loading.gif" alt="loading" />
      </div><br/><br/><br/>
    </section>
{% endfor %}
{% endblock %}
{% block js %}
<script type="text/javascript">
    function load_content(){
        $("#countdown").addClass('alert');
        $("#countdown").removeClass('alert-error');
        $("#countdown").removeClass('alert-info');
        $("#countdown").addClass('alert-warning');
        
        $("#countdown").html('Data is refreshing...')
        $('.section-head').each(function() {
           var id = $(this).attr('name');
           // put the loading animation in place
           $('#content-' + id).html('<img src="{{MEDIA_URL}}img/loading.gif" alt="loading" />');
           // load the URL
           $('#content-' + id).load('./get-group/' + id + '/');
        });
        
        countdown(120);
        // if you click on a 'site', it should show information about that site underneath it
        
    }
    
    function countdown(seconds){
        $("#countdown").removeClass('alert-error');
        $("#countdown").removeClass('alert-warning');
        $("#countdown").addClass('alert-info');
        var seconds = seconds;
        setTimeout(update_countdown(), 1000);
        function update_countdown(){
            seconds--;
            
            if (seconds > 0) {
                $("#countdown").text("Data will refresh in " + seconds + " seconds");
                   setTimeout(update_countdown, 1000);
               
                if (seconds == 15){
                    $("#countdown").removeClass('alert-error');
                    $("#countdown").removeClass('alert-info');
                    $("#countdown").addClass('alert-warning');
                    }
                if (seconds == 5){
                    $("#countdown").removeClass('alert-warning');
                    $("#countdown").removeClass('alert-info');
                    $("#countdown").addClass('alert-error');
                    }
                } 
            else {
                load_content();
            }
        }
    }
    
    $(function() {
        load_content();
    });
    
</script>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block section %}

<div class="row">
    <div class="span12">

       <form class="form-horizontal well" method="post" action="{% url login %}">
           {% csrf_token %}
        <fieldset>
          <legend>Login</legend>
          <div class="control-group">
            <label for="username" class="control-label">Username</label>
            <div class="controls">
              <input type="text" id="" class="input-xlarge" name="username" />
            </div>
          </div>
          <div class="control-group">
            <label for="password" class="control-label">Password</label>
            <div class="controls">
              <input type="password" id="password" class="input-xlarge" name="password" />
            </div>
          </div>
          <div class="form-actions">
            <button class="btn btn-primary" type="submit">Login</button>
          </div>
        </fieldset>
      </form>
    </div>
</div>
    

{% endblock %}
{% block js %}

{% endblock %}

templates/outage.html
{% extends "base.html" %}{% load readable_time %}
{% block section %}

    <section id="outage" class="section-head" name="outage">
      <div class="page-header">
          <h1>Outage {% if outage.code %}#{{outage.code}}{% endif %}</h1>
      </div>
      <div class="row">
        <div class="span4">
            <div class="well">
                Outage Started: {{outage.start_time}}<br/>
                Outage Ended: 
                {% if outage.end_time %}{{outage.end_time}}
                {% else %}<span class="label label-important">Current</span>
                {% endif %}
                <br/><br/>
                The following systems were effected by this outage: <br/>
                {% for site in outage.outagesites_set.all %}
                    <span class="label{% if site.primary %} label-important{% endif %}">{{site.site.title}}</span> 
                {% endfor %}
                {% if outage.end_time %}
                <br/><br/>
                This outage lasted {{outage.seconds_down|readable_time}}
                {% endif %}
            </div>

            
        </div>
        <div class="span8">
            <h3>Outage log file</h3>
            {{outage.content|linebreaksbr}}
        </div>
    </div>
      <br/><br/><br/>
    </section>

{% endblock %}
{% block js %}

{% endblock %}

templates/outages.html
{% extends "base.html" %}{% load paginator %}{% load readable_time %}
{% block section %}

    <section id="outage" class="section-head" name="outage">
      <div class="page-header">
          <h1>Outages</h1>
      </div>
      <div class="row">
        <div class="span12">
            <table class="table table-bordered table-striped">
                <thead>
                  <tr>
                    <th>Code</th>
                    <th>Start Time</th>
                    <th>End Time</th>
                    <th>Systems</th>
                    <th>Time Down</th>
                    <th>View</th>
                  </tr>
                </thead>
                <tbody>
                        {% for outage in outages %}
                          <tr>
                            <td>{% if outage.code %}#{{outage.code}}{% else %}&nbsp;{% endif %}</td>
                            <td>{{outage.start_time}}</td>
                            <td>{% if outage.end_time %}{{outage.end_time}}{% else %}<span class="label label-important">CURRENT</span> {% endif %}</td>
                            <td>
                                
                                {% for site in outage.outagesites_set.all %}
                                    <span class="label{% if site.primary %} label-important{% endif %}">{{site.site.title}}</span> 
                                {% endfor %}
                            </td>
                            <td>
                                {% if outage.end_time %}
                                    {{outage.seconds_down|readable_time}}
                                {% else %}
                                    <span class="label label-important">CURRENT</span> 
                                {% endif %}
                            </td>
                            <td><a class="btn btn-small" href="{% url outage outage.pk %}">View</a></td>
                          </tr>
                        {% endfor %}
                </tbody>
              </table>
            {% paginate outages %}
        </div>
    </div>
      <br/><br/><br/>
    </section>

{% endblock %}
{% block js %}

{% endblock %}

templates/views.html
{% for r in recent %}
    <span class="control-group{% if r.status_code in good_codes %} success{% else %} error{% endif %}">
        <span class="label label-{% if r.status_code in good_codes %}success{% else %}important{% endif %}">{{r.status_code}}</span>
        <span class="help-inline">{{r.attempt_time|date:"l, jS F"}} at {{r.attempt_time|date:"g:ia"}}</span>
    </span><br/>
{% empty %}
No recent views have been recorded
{% endfor %}